function buildNetworkWatcherSteps() {
  return [
    {
      name: "base",
      source: [
        "if(window.__kissDiag&&window.__kissDiag.version==='safe-v2'){emit('watcher-step-ok',{already:true,dom:window.__kissDiag.domState?window.__kissDiag.domState():{}});return 'already';}",
        "var d=window.__kissDiag={version:'safe-v2',recent:[],playerActivityByUid:{},counters:{fetch:0,xhr:0,importantFetch:0,importantXhr:0,roomChange:0,roomFollow:0,kissAnswer:0,kissAnswers:{},lastKissStatus:0,lastKissResult:null,lastKissRoomId:'',socketCreate:0,socketOpen:0,socketClose:0,socketError:0,socketSend:0,socketMessage:0,lastEmit:Date.now()},activity:{trusted:0,untrusted:0,manualClicks:0,manualKeys:0,manualTouches:0,syntheticClicks:0,moves:0,lastType:'',lastTrusted:null,lastAt:0,lastTarget:'',lastEmit:Date.now()},roster:{last:null,lastEmit:Date.now(),ownWasPresent:false,missingSince:0}};",
        "d.now=function(){return Date.now();};",
        "d.cleanUrl=function(url){try{var u=new URL(String(url||''),location.href);return u.pathname+(u.search||'');}catch(_){return String(url||'').slice(0,220);}};",
        "d.fullUrl=function(url){try{return String(new URL(String(url||''),location.href).href).slice(0,500);}catch(_){return String(url||'').slice(0,500);}};",
        "d.domState=function(){try{return {readyState:document.readyState,visibility:document.visibilityState,players:document.querySelectorAll('.player[data-uid][data-pid]:not(.player-graphics)').length,startButton:!!document.querySelector('button.splash--start-button.js-start-kiss'),lastRoomId:String(window.__KISS_LAST_ROOM_ID||localStorage.getItem('kiss_hidden_last_room_id')||'').slice(0,40),authUserId:String(window.__KISS_AUTH_USER_ID||localStorage.getItem('kiss_auth_user_id')||'').slice(0,40),hasFocus:document.hasFocus&&document.hasFocus()};}catch(_){return {};}};",
        "d.stack=function(){try{return String((new Error()).stack||'').split('\\n').slice(2,7).map(function(line){return line.trim().slice(0,160);});}catch(_){return [];}};",
        "d.remember=function(kind,payload){try{d.recent.push(Object.assign({kind:kind,at:d.now(),href:d.cleanUrl(location.href)},payload||{}));if(d.recent.length>12)d.recent.shift();}catch(_){}};",
        "d.recentCopy=function(){try{return d.recent.slice(-6);}catch(_){return [];}};",
        "d.notePlayer=function(uid,kind,source){try{var id=String(uid||'').trim();if(!/^\\d+$/.test(id)||id==='0')return;var at=d.now();var roomId=String(window.__KISS_LAST_ROOM_ID||localStorage.getItem('kiss_hidden_last_room_id')||'').slice(0,40);var entry=d.playerActivityByUid[id]||{uid:id};entry.lastRoomId=roomId;entry.source=source||kind;entry.updatedAt=at;if(kind==='seen')entry.lastSeenAt=at;if(kind==='join'){entry.lastJoinAt=at;entry.lastSeenAt=at;}if(kind==='left'){entry.lastLeftAt=at;entry.lastExitAt=at;}if(kind==='exit')entry.lastExitAt=at;d.playerActivityByUid[id]=entry;}catch(_){}};",
        "d.notePlayers=function(ids,kind,source){try{(ids||[]).forEach(function(uid){d.notePlayer(uid,kind,source);});}catch(_){}};",
        "d.extractUserIds=function(text){var out=[];try{String(text||'').replace(/\\b\\d{5,12}\\b/g,function(match){if(out.indexOf(match)===-1)out.push(match);return match;});}catch(_){}return out.slice(0,12);};",
        "d.emitNet=function(kind,payload){try{console.log('__KISS_NET_EVENT__'+JSON.stringify(Object.assign({kind:kind,href:d.cleanUrl(location.href),at:d.now()},payload||{})));}catch(_){}};",
        "d.emitNav=function(kind,payload){try{console.log('__KISS_NAV_EVENT__'+JSON.stringify(Object.assign({kind:kind,href:d.cleanUrl(location.href),at:d.now()},payload||{})));}catch(_){}};",
        "d.emitActivity=function(kind,payload){try{console.log('__KISS_ACTIVITY_EVENT__'+JSON.stringify(Object.assign({kind:kind,href:d.cleanUrl(location.href),at:d.now()},payload||{})));}catch(_){}};",
        "d.emitRoster=function(kind,payload){try{console.log('__KISS_ROSTER_EVENT__'+JSON.stringify(Object.assign({kind:kind,href:d.cleanUrl(location.href),at:d.now()},payload||{})));}catch(_){}};",
        "d.validRoomId=function(v){var t=String(v||'').trim();return /^\\d+$/.test(t)&&t!=='0'?t:'';};",
        "d.roomSourceRank=function(source,confidence){var s=String(source||'');var ranks={'get_status.response':500,'roulette_answer.response':420,'roulette_answer.request':400,'blackList.getProfiles.response':300,'network-room':230,'room-event':180,'room-refresh':170,webview:160,snapshot:120,localStorage:30,dom:20,href:10};if(Object.prototype.hasOwnProperty.call(ranks,s))return ranks[s];return String(confidence||'')==='high'?200:String(confidence||'')==='medium'?100:0;};",
        "d.rememberRoom=function(roomId,source,confidence,extra){try{var id=d.validRoomId(roomId);if(!id)return '';var at=d.now();var src=source||'network-room';var conf=confidence||'high';var prev=d.validRoomId(window.__KISS_LAST_ROOM_ID);var prevAt=Number(window.__KISS_LAST_ROOM_ID_AT||0);var prevRank=Number(window.__KISS_LAST_ROOM_SOURCE_RANK||0);var nextRank=d.roomSourceRank(src,conf);if(prev&&prevAt&&at-prevAt<180000&&nextRank<prevRank)return prev;window.__KISS_LAST_ROOM_ID=id;window.__KISS_LAST_ROOM_ID_AT=at;window.__KISS_LAST_ROOM_SOURCE=src;window.__KISS_LAST_ROOM_SOURCE_RANK=nextRank;localStorage.setItem('kiss_hidden_last_room_id',id);localStorage.setItem('kiss_hidden_last_room_id_at',String(at));localStorage.setItem('kiss_hidden_last_room_source',src);localStorage.setItem('kiss_hidden_last_room_source_rank',String(nextRank));var payload=Object.assign({roomId:id,source:src,confidence:conf,at:at},extra||{});console.log('__KISS_ROOM_ID__'+JSON.stringify(payload));d.emitNet('network-room-detected',payload);return id;}catch(_){return '';}};",
        "d.isKissAnswerUrl=function(url){return String(url||'').indexOf('/api/room/roulette_answer')!==-1;};",
        "d.isGetStatusUrl=function(url){return String(url||'').indexOf('/api/room/get_status')!==-1;};",
        "d.isBlackListProfilesUrl=function(url){return String(url||'').indexOf('/api/blackList/getProfiles')!==-1;};",
        "d.isImportantUrl=function(url){var t=String(url||'');return t.indexOf('/api/room/change')!==-1||t.indexOf('/api/room/sit_down_to_friend')!==-1||t.indexOf('/api/user/login')!==-1||t.indexOf('/ajax/product/wheel_of_fortune')!==-1||d.isKissAnswerUrl(t)||d.isGetStatusUrl(t)||d.isBlackListProfilesUrl(t)||t.indexOf('/game/room')!==-1;};",
        "d.roomId=function(data){try{return String((data&&data.status&&(data.status.room_id||data.status.roomId))||data.room_id||data.roomId||'');}catch(_){return '';}};",
        "d.compactJson=function(text){try{var data=JSON.parse(String(text||''));return {result:data&&data.result,error:data&&data.error,roomId:d.roomId(data),type:data&&data.type,userId:data&&data.userId};}catch(_){return {};}};",
        "d.bodyInfo=function(body){try{var text=typeof body==='string'?body:(body&&body.toString?body.toString():'');if(!text)return {};var params=new URLSearchParams(text);var out={};['friend_id','roomId','room_id','answer','type'].forEach(function(k){var v=params.get(k);if(v!=null)out[k]=String(v).slice(0,80);});return out;}catch(_){return {};}};",
        "d.trackRoomFromNetwork=function(url,transport,body,response){try{var t=String(url||'');var info=d.bodyInfo(body);if(d.isKissAnswerUrl(t)){var requestRoom=d.validRoomId(info.roomId||info.room_id);if(requestRoom)d.rememberRoom(requestRoom,'roulette_answer.request','high',{url:d.cleanUrl(t),transport:transport,body:info});var responseRoom=d.validRoomId(response&&response.roomId);if(responseRoom)d.rememberRoom(responseRoom,'roulette_answer.response','high',{url:d.cleanUrl(t),transport:transport,response:response});return;}var source='';if(d.isGetStatusUrl(t))source='get_status.response';else if(d.isBlackListProfilesUrl(t))source='blackList.getProfiles.response';if(source&&response&&response.roomId)d.rememberRoom(response.roomId,source,'high',{url:d.cleanUrl(t),transport:transport,response:response});}catch(_){}};",
        "d.emitPulse=function(force){try{var c=d.counters,at=d.now();if(!force&&at-c.lastEmit<30000)return;c.lastEmit=at;d.emitNet('network-summary',{fetch:c.fetch,xhr:c.xhr,importantFetch:c.importantFetch,importantXhr:c.importantXhr,roomChange:c.roomChange,roomFollow:c.roomFollow,kissAnswer:c.kissAnswer,kissAnswers:c.kissAnswers,lastKissStatus:c.lastKissStatus,lastKissResult:c.lastKissResult,lastKissRoomId:c.lastKissRoomId,socketCreate:c.socketCreate,socketOpen:c.socketOpen,socketClose:c.socketClose,socketError:c.socketError,socketSend:c.socketSend,socketMessage:c.socketMessage,dom:d.domState()});c.fetch=c.xhr=c.importantFetch=c.importantXhr=c.roomChange=c.roomFollow=c.kissAnswer=c.socketCreate=c.socketOpen=c.socketClose=c.socketError=c.socketSend=c.socketMessage=0;c.kissAnswers={};}catch(_){}};",
        "d.mark=function(url,kind){try{var t=String(url||''),c=d.counters;if(kind==='fetch')c.fetch++;if(kind==='xhr')c.xhr++;if(d.isImportantUrl(t)){if(kind==='fetch')c.importantFetch++;if(kind==='xhr')c.importantXhr++;}if(t.indexOf('/api/room/change')!==-1)c.roomChange++;if(t.indexOf('/api/room/sit_down_to_friend')!==-1)c.roomFollow++;if(d.isKissAnswerUrl(t))c.kissAnswer++;d.emitPulse(false);}catch(_){}};",
        "d.emitNet('network-installed',{dom:d.domState()});"
      ].join("")
    },
    {
      name: "nav",
      source: [
        "var d=window.__kissDiag;if(!d||d.navInstalled){emit('watcher-step-ok',{already:!!(d&&d.navInstalled),missingBase:!d,dom:d&&d.domState?d.domState():{}});return 'missing-base-or-already';}d.navInstalled=true;",
        "function suspicious(url){var t=String(url||'');return t.indexOf('/game/room?=undefined')!==-1||t.indexOf('=undefined')!==-1;}",
        "function nav(kind,url,extra){try{var target=d.cleanUrl(url||location.href);d.remember('nav-'+kind,{url:target});if(kind==='history-push'||kind==='history-replace'||kind==='anchor-click'||kind==='form-submit'||kind==='beforeunload'||kind==='pagehide'||kind==='popstate'||kind==='hashchange'||suspicious(target)||suspicious(location.href)){d.emitNav(kind,Object.assign({url:target,fullUrl:d.fullUrl(url||location.href),suspicious:suspicious(target)||suspicious(location.href),dom:d.domState(),recent:d.recentCopy(),stack:d.stack()},extra||{}));}}catch(_){}}",
        "try{var hp=history.pushState;history.pushState=function(state,title,url){nav('history-push',url,{hasState:state!=null});return hp.apply(this,arguments);};}catch(error){d.emitNav('history-push-hook-failed',{error:String(error&&error.message?error.message:error)});}",
        "try{var hr=history.replaceState;history.replaceState=function(state,title,url){nav('history-replace',url,{hasState:state!=null});return hr.apply(this,arguments);};}catch(error){d.emitNav('history-replace-hook-failed',{error:String(error&&error.message?error.message:error)});}",
        "document.addEventListener('click',function(event){try{var el=event.target&&event.target.closest&&event.target.closest('a[href],button,[role=button],.js-menu-changeroom,.js-start-kiss,.player,[data-room-id],[data-roomid]');if(!el)return;var a=el.matches&&el.matches('a[href]')?el:el.closest&&el.closest('a[href]');var text=String(el.textContent||'').replace(/\\s+/g,' ').trim().slice(0,100);var meta={tag:String(el.tagName||'').toLowerCase(),className:String(el.className||'').replace(/\\s+/g,' ').slice(0,140),text:text,button:event.button,dom:d.domState()};if(a)nav('anchor-click',a.getAttribute('href'),meta);else if(/oyna|play|room|oda|change|masa|profil|profile/i.test(text+' '+meta.className))d.emitNav('ui-click',Object.assign(meta,{recent:d.recentCopy(),stack:d.stack()}));}catch(_){}},true);",
        "document.addEventListener('submit',function(event){try{var form=event.target;nav('form-submit',form&&form.getAttribute&&form.getAttribute('action')||location.href,{method:form&&form.method,dom:d.domState()});}catch(_){}},true);",
        "document.addEventListener('visibilitychange',function(){d.emitNav('visibilitychange',{visibility:document.visibilityState,dom:d.domState(),recent:d.recentCopy()});});",
        "window.addEventListener('beforeunload',function(){d.emitPulse(true);nav('beforeunload',location.href);});",
        "window.addEventListener('pagehide',function(event){d.emitPulse(true);nav('pagehide',location.href,{persisted:!!(event&&event.persisted)});});",
        "window.addEventListener('popstate',function(){nav('popstate',location.href);});",
        "window.addEventListener('hashchange',function(){nav('hashchange',location.href);});",
        "window.addEventListener('error',function(event){d.emitNav('window-error',{message:String(event&&event.message||'').slice(0,220),source:d.cleanUrl(event&&event.filename||''),line:event&&event.lineno});});",
        "window.addEventListener('unhandledrejection',function(event){d.emitNav('unhandled-rejection',{reason:String(event&&event.reason&&event.reason.message?event.reason.message:event&&event.reason||'').slice(0,220)});});",
        "setInterval(function(){try{if(suspicious(location.href))d.emitNav('undefined-route-heartbeat',{url:d.cleanUrl(location.href),fullUrl:d.fullUrl(location.href),dom:d.domState()});}catch(_){}},30000);",
        "d.emitNet('nav-installed',{dom:d.domState()});"
      ].join("")
    },
    {
      name: "network",
      source: [
        "var d=window.__kissDiag;if(!d||d.networkInstalled){emit('watcher-step-ok',{already:!!(d&&d.networkInstalled),missingBase:!d,dom:d&&d.domState?d.domState():{}});return 'missing-base-or-already';}d.networkInstalled=true;",
        "var originalFetch=window.fetch;if(typeof originalFetch==='function'){window.fetch=function(input,init){var url=(input&&input.url)||input;var method=(init&&init.method)||(input&&input.method)||'GET';var important=d.isImportantUrl(url);var routineKiss=d.isKissAnswerUrl(url);d.mark(url,'fetch');d.remember('fetch',{url:d.cleanUrl(url),method:String(method||'GET').toUpperCase(),important:important});var started=d.now();if(important&&!routineKiss)d.emitNet('fetch-start',{url:d.cleanUrl(url),fullUrl:d.fullUrl(url),method:String(method||'GET').toUpperCase(),body:d.bodyInfo(init&&init.body),dom:d.domState(),stack:d.stack()});var promise=originalFetch.apply(this,arguments);if(important){promise.then(function(res){try{res.clone().text().then(function(text){var response=d.compactJson(text);d.remember('fetch-end',{url:d.cleanUrl(url),status:res.status,roomId:response.roomId,error:response.error});d.trackRoomFromNetwork(url,'fetch',init&&init.body,response);if(routineKiss){var info=d.bodyInfo(init&&init.body);d.counters.kissAnswers[String(info.answer||'?')]=(d.counters.kissAnswers[String(info.answer||'?')]||0)+1;d.counters.lastKissStatus=res.status;d.counters.lastKissResult=response.result;d.counters.lastKissRoomId=response.roomId||String(info.roomId||'');if(!res.ok||response.error)d.emitNet('fetch-end',{url:d.cleanUrl(url),method:String(method||'GET').toUpperCase(),status:res.status,ok:!!res.ok,durationMs:d.now()-started,response:response});d.emitPulse(false);return;}d.emitNet('fetch-end',{url:d.cleanUrl(url),method:String(method||'GET').toUpperCase(),status:res.status,ok:!!res.ok,durationMs:d.now()-started,response:response,dom:d.domState()});}).catch(function(error){d.emitNet('fetch-read-error',{url:d.cleanUrl(url),error:String(error&&error.message?error.message:error)});});}catch(error){d.emitNet('fetch-log-error',{url:d.cleanUrl(url),error:String(error&&error.message?error.message:error)});}}).catch(function(error){d.emitNet('fetch-error',{url:d.cleanUrl(url),method:String(method||'GET').toUpperCase(),durationMs:d.now()-started,error:String(error&&error.message?error.message:error),dom:d.domState(),stack:d.stack()});});}return promise;};}",
        "var OriginalXHR=window.XMLHttpRequest;if(typeof OriginalXHR==='function'){var open=OriginalXHR.prototype.open;var send=OriginalXHR.prototype.send;OriginalXHR.prototype.open=function(method,url){try{this.__kissNetUrl=String(url||'');this.__kissNetMethod=String(method||'GET');}catch(_){}return open.apply(this,arguments);};OriginalXHR.prototype.send=function(body){try{var xhr=this;var url=xhr.__kissNetUrl||'';var important=d.isImportantUrl(url);var routineKiss=d.isKissAnswerUrl(url);d.mark(url,'xhr');d.remember('xhr',{url:d.cleanUrl(url),method:String(xhr.__kissNetMethod||'GET').toUpperCase(),important:important});var started=d.now();if(important&&!routineKiss)d.emitNet('xhr-start',{url:d.cleanUrl(url),fullUrl:d.fullUrl(url),method:String(xhr.__kissNetMethod||'GET').toUpperCase(),body:d.bodyInfo(body),dom:d.domState(),stack:d.stack()});if(important){xhr.addEventListener('load',function(){var response=d.compactJson(xhr.responseText);d.remember('xhr-end',{url:d.cleanUrl(url),status:xhr.status,roomId:response.roomId,error:response.error});d.trackRoomFromNetwork(url,'xhr',body,response);if(routineKiss){var info=d.bodyInfo(body);d.counters.kissAnswers[String(info.answer||'?')]=(d.counters.kissAnswers[String(info.answer||'?')]||0)+1;d.counters.lastKissStatus=xhr.status;d.counters.lastKissResult=response.result;d.counters.lastKissRoomId=response.roomId||String(info.roomId||'');if(xhr.status<200||xhr.status>=300||response.error)d.emitNet('xhr-end',{url:d.cleanUrl(url),method:String(xhr.__kissNetMethod||'GET').toUpperCase(),status:xhr.status,durationMs:d.now()-started,response:response});d.emitPulse(false);return;}d.emitNet('xhr-end',{url:d.cleanUrl(url),method:String(xhr.__kissNetMethod||'GET').toUpperCase(),status:xhr.status,durationMs:d.now()-started,response:response,dom:d.domState()});});xhr.addEventListener('error',function(){d.emitNet('xhr-error',{url:d.cleanUrl(url),method:String(xhr.__kissNetMethod||'GET').toUpperCase(),durationMs:d.now()-started,dom:d.domState()});});xhr.addEventListener('abort',function(){d.emitNet('xhr-abort',{url:d.cleanUrl(url),method:String(xhr.__kissNetMethod||'GET').toUpperCase(),durationMs:d.now()-started,dom:d.domState()});});}}catch(error){d.emitNet('xhr-hook-error',{error:String(error&&error.message?error.message:error)});}return send.apply(this,arguments);};}",
        "d.emitNet('fetch-xhr-installed',{dom:d.domState()});"
      ].join("")
    },
    {
      name: "socket",
      source: [
        "var d=window.__kissDiag;if(!d||d.socketInstalled){emit('watcher-step-ok',{already:!!(d&&d.socketInstalled),missingBase:!d,dom:d&&d.domState?d.domState():{}});return 'missing-base-or-already';}d.socketInstalled=true;",
        "var OriginalWebSocket=window.WebSocket;if(typeof OriginalWebSocket==='function'){window.WebSocket=function(url,protocols){var ws=protocols!==undefined?new OriginalWebSocket(url,protocols):new OriginalWebSocket(url);try{var safe=d.cleanUrl(url);var sent=0;var received=0;var socketPattern=/room|change|follow|roulette|kiss|join|leave|left|exit|seat|user|kick|replace|table|authorization/i;d.counters.socketCreate++;d.emitNet('socket-create',{url:safe,dom:d.domState(),stack:d.stack()});d.remember('socket-create',{url:safe});var originalSend=ws.send;ws.send=function(data){sent++;d.counters.socketSend++;try{var text=typeof data==='string'?data:'';if(text&&socketPattern.test(text)){d.emitNet('socket-send',{url:safe,size:String(text).length,preview:text.slice(0,260),dom:d.domState()});d.remember('socket-send',{url:safe,preview:text.slice(0,100)});}}catch(_){}return originalSend.apply(ws,arguments);};ws.addEventListener('message',function(event){received++;d.counters.socketMessage++;try{var text=typeof event.data==='string'?event.data:'';if(text&&socketPattern.test(text)){var ids=d.extractUserIds(text);var exitish=/exit|leave|left/i.test(text);var joinish=/join|enter|seat|sit/i.test(text);if(exitish)d.notePlayers(ids,'exit','socket-message');else if(joinish)d.notePlayers(ids,'join','socket-message');d.emitNet('socket-message',{url:safe,size:text.length,preview:text.slice(0,320),ids:ids.slice(0,8),exitish:exitish,joinish:joinish,dom:d.domState()});d.remember('socket-message',{url:safe,preview:text.slice(0,100),ids:ids.slice(0,6),exitish:exitish,joinish:joinish});}}catch(_){} });ws.addEventListener('open',function(){d.counters.socketOpen++;d.emitNet('socket-open',{url:safe});});ws.addEventListener('close',function(event){d.counters.socketClose++;d.emitPulse(true);d.emitNet('socket-close',{url:safe,code:event&&event.code,reason:String(event&&event.reason||'').slice(0,120),wasClean:!!(event&&event.wasClean),sent:sent,received:received,dom:d.domState(),recent:d.recentCopy()});});ws.addEventListener('error',function(){d.counters.socketError++;d.emitPulse(true);d.emitNet('socket-error',{url:safe,sent:sent,received:received,dom:d.domState(),recent:d.recentCopy()});});}catch(error){d.emitNet('socket-hook-error',{error:String(error&&error.message?error.message:error)});}return ws;};try{window.WebSocket.prototype=OriginalWebSocket.prototype;window.WebSocket.CONNECTING=OriginalWebSocket.CONNECTING;window.WebSocket.OPEN=OriginalWebSocket.OPEN;window.WebSocket.CLOSING=OriginalWebSocket.CLOSING;window.WebSocket.CLOSED=OriginalWebSocket.CLOSED;}catch(_){}}",
        "d.emitNet('socket-installed',{hasWebSocket:typeof OriginalWebSocket==='function'});"
      ].join("")
    },
    {
      name: "activity",
      source: [
        "var d=window.__kissDiag;if(!d||d.activityInstalled){emit('watcher-step-ok',{already:!!(d&&d.activityInstalled),missingBase:!d,dom:d&&d.domState?d.domState():{}});return 'missing-base-or-already';}d.activityInstalled=true;",
        "function shortTarget(el){try{if(!el)return '';var holder=el.closest&&el.closest('.player,[data-uid],button,a,[role=button],input,textarea,select');var target=holder||el;var cls=String(target.className||'').replace(/\\s+/g,' ').trim().slice(0,90);var uid=target.getAttribute&&target.getAttribute('data-uid')||target.closest&&target.closest('[data-uid]')&&target.closest('[data-uid]').getAttribute('data-uid')||'';return String(target.tagName||'').toLowerCase()+(cls?'.'+cls:'')+(uid?'#uid:'+uid:'');}catch(_){return '';}}",
        "function activityPulse(force){try{var a=d.activity,at=d.now();if(!force&&at-a.lastEmit<30000)return;a.lastEmit=at;d.emitActivity('activity-pulse',{trusted:a.trusted,untrusted:a.untrusted,manualClicks:a.manualClicks,manualKeys:a.manualKeys,manualTouches:a.manualTouches,syntheticClicks:a.syntheticClicks,moves:a.moves,lastType:a.lastType,lastTrusted:a.lastTrusted,lastAgeMs:a.lastAt?at-a.lastAt:null,lastTarget:a.lastTarget,dom:d.domState()});a.trusted=a.untrusted=a.manualClicks=a.manualKeys=a.manualTouches=a.syntheticClicks=a.moves=0;}catch(_){}}",
        "function noteActivity(event){try{var a=d.activity;var trusted=!!(event&&event.isTrusted);var type=String(event&&event.type||'');if(trusted)a.trusted++;else a.untrusted++;if(type==='click'&&trusted)a.manualClicks++;if(type==='click'&&!trusted)a.syntheticClicks++;if(/^key/.test(type)&&trusted)a.manualKeys++;if(/^touch/.test(type)&&trusted)a.manualTouches++;if(type==='mousemove'||type==='pointermove')a.moves++;a.lastType=type;a.lastTrusted=trusted;a.lastAt=d.now();a.lastTarget=shortTarget(event&&event.target);if(type==='click'||type==='pointerdown'||type==='keydown'||type==='touchstart')d.emitActivity('activity-event',{type:type,trusted:trusted,target:a.lastTarget,dom:d.domState()});activityPulse(false);}catch(_){}}",
        "['mousemove','pointermove','mousedown','pointerdown','click','keydown','touchstart'].forEach(function(type){try{document.addEventListener(type,noteActivity,true);}catch(_){}});",
        "document.addEventListener('visibilitychange',function(){activityPulse(true);});window.addEventListener('focus',function(){d.emitActivity('window-focus',{dom:d.domState()});});window.addEventListener('blur',function(){d.emitActivity('window-blur',{dom:d.domState()});});setInterval(function(){activityPulse(false);},3000);",
        "d.emitActivity('activity-installed',{dom:d.domState()});"
      ].join("")
    },
    {
      name: "roster",
      source: [
        "var d=window.__kissDiag;if(!d||d.rosterInstalled){emit('watcher-step-ok',{already:!!(d&&d.rosterInstalled),missingBase:!d,dom:d&&d.domState?d.domState():{}});return 'missing-base-or-already';}d.rosterInstalled=true;",
        "function numeric(v){var t=String(v||'').trim();return /^\\d+$/.test(t)&&t!=='0'?t:'';}",
        "function selectorCounts(){try{return {playerData:document.querySelectorAll('.player[data-uid][data-pid]:not(.player-graphics)').length};}catch(_){return {};}}",
        "function nearestPlayer(el){try{return el&&el.closest&&el.closest('.js-player,.player__wrap,.player,[data-pid],[data-uid]')||el;}catch(_){return el;}}",
        "function uidFrom(el){try{if(!el)return '';var direct=numeric(el.getAttribute&&el.getAttribute('data-uid'));if(direct)return direct;var holder=nearestPlayer(el);direct=numeric(holder&&holder.getAttribute&&holder.getAttribute('data-uid'));if(direct)return direct;var child=holder&&holder.querySelector&&holder.querySelector('[data-uid]');direct=numeric(child&&child.getAttribute&&child.getAttribute('data-uid'));if(direct)return direct;var parent=el.closest&&el.closest('[data-uid]');return numeric(parent&&parent.getAttribute&&parent.getAttribute('data-uid'));}catch(_){return '';}}",
        "function pidFrom(el){try{var holder=nearestPlayer(el);return String((holder&&holder.getAttribute&&holder.getAttribute('data-pid'))||(el&&el.getAttribute&&el.getAttribute('data-pid'))||'').slice(0,40);}catch(_){return '';}}",
        "function topfaceRoomId(){try{for(var i=0;i<localStorage.length;i++){var key=String(localStorage.key(i)||'');if(key.indexOf('topface_stprev_room_id')!==0)continue;var raw=localStorage.getItem(key);var direct=numeric(raw);if(direct)return direct;try{var parsed=JSON.parse(raw);var nested=numeric(parsed&&parsed.data&&parsed.data.value);if(nested)return nested;}catch(_){}}}catch(_){}return '';}",
        "function roomId(){try{return numeric(window.__KISS_LAST_ROOM_ID)||topfaceRoomId()||numeric(localStorage.getItem('kiss_hidden_last_room_id'));}catch(_){return '';}}",
        "function ownUidFromDom(map){try{var stored=numeric(window.__KISS_AUTH_USER_ID||localStorage.getItem('kiss_auth_user_id'));if(stored)return stored;try{var dl=Array.isArray(window.dataLayer)?window.dataLayer:[];for(var i=0;i<dl.length;i++){var item=dl[i]||{};var dataId=numeric(item.userID||item.userId||item.uid||item.id);if(dataId)return dataId;}}catch(_){}var track=numeric(window._trackJs&&window._trackJs.userId);if(track)return track;var active=numeric(window.__KISS_ACTIVE_GUARD_STATE&&window.__KISS_ACTIVE_GUARD_STATE.myUid);if(active)return active;var own=document.querySelector('.js-player--me,[data-is-me=\"true\"],[data-own=\"true\"],.is-me,.player--me,.me');var ownId=uidFrom(own);if(ownId)return ownId;var keys=Object.keys(map||{});return keys.length===1?keys[0]:'';}catch(_){return '';}}",
        "function playerInfo(el){try{var holder=nearestPlayer(el);var uid=uidFrom(holder||el);if(!uid)return null;var pid=pidFrom(holder||el);var cls=String((holder&&holder.className)||el.className||'').replace(/\\s+/g,' ').trim().slice(0,140);var text=String((holder&&holder.textContent)||el.textContent||'').replace(/\\s+/g,' ').trim().slice(0,240);var vip=/vip/i.test(cls)||/vip/i.test(text);var league='';var m=(cls+' '+text).match(/(?:lig|league|level|lvl|rank)\\s*[:#-]?\\s*([0-9]{1,2})/i);if(m)league=m[1];return {uid:uid,pid:pid,className:cls,vip:vip,league:league};}catch(_){return null;}}",
        "function readRoster(){try{var map={};var candidates=Array.from(document.querySelectorAll('.player[data-uid][data-pid]:not(.player-graphics)'));candidates.forEach(function(el){var info=playerInfo(el);if(info&&!map[info.uid])map[info.uid]=info;});var ids=Object.keys(map).sort();var me=ownUidFromDom(map);return {roomId:roomId(),ownUid:me,count:ids.length,ids:ids,players:map,ownPresent:!!(me&&map[me]),selectors:selectorCounts(),dom:d.domState()};}catch(_){return {roomId:roomId(),ownUid:ownUidFromDom({}),count:0,ids:[],players:{},ownPresent:false,selectors:{},dom:d.domState()};}}",
        "function diffIds(prev,next){var out=[];try{var p={};(prev||[]).forEach(function(id){p[id]=true;});(next||[]).forEach(function(id){if(!p[id])out.push(id);});}catch(_){}return out;}function compactPlayers(snapshot,ids){var out=[];try{(ids||[]).slice(0,12).forEach(function(id){var p=snapshot&&snapshot.players&&snapshot.players[id];if(p)out.push({uid:p.uid,pid:p.pid,vip:p.vip,league:p.league,className:p.className});});}catch(_){}return out;}",
        "function observeRoster(force){try{var at=d.now();var snap=readRoster();var prev=d.roster.last;var joined=prev?diffIds(prev.ids,snap.ids):[];var left=prev?diffIds(snap.ids,prev.ids):[];d.notePlayers(snap.ids,'seen','roster');d.notePlayers(joined,'join','roster-diff');d.notePlayers(left,'left','roster-diff');var base={roomId:snap.roomId,ownUid:snap.ownUid,count:snap.count,ownPresent:snap.ownPresent,ids:snap.ids.slice(0,14)};var changed=!prev||joined.length||left.length||prev.roomId!==snap.roomId||prev.ownPresent!==snap.ownPresent;var payload=Object.assign({},base,{joined:joined,left:left});if(force||changed)d.emitRoster('roster-diff',payload);if(joined.length)d.emitRoster('players-joined',Object.assign({},payload,{joinedPlayers:compactPlayers(snap,joined)}));if(left.length)d.emitRoster('players-left',Object.assign({},payload,{leftPlayers:compactPlayers(prev,left)}));if(snap.ownPresent&&!d.roster.ownWasPresent)d.emitRoster('own-player-present',base);if(!snap.ownPresent&&snap.ownUid&&prev&&prev.ownPresent){d.roster.missingSince=at;var recentSocket=[];try{recentSocket=d.recentCopy().filter(function(e){return at-e.at<20000&&String(e.kind||'').indexOf('socket')!==-1;});}catch(_){}var lost=Object.assign({},payload,{missingSince:d.roster.missingSince,possibleVipDisplacement:!!(joined.length&&!d.counters.roomChange&&!d.counters.roomFollow),recentSocket:recentSocket,dom:snap.dom});d.emitRoster('own-seat-lost',lost);if(lost.possibleVipDisplacement)d.emitRoster('possible-vip-displacement',lost);}if(!snap.ownPresent&&snap.ownUid&&(!prev||!prev.ownPresent)&&at-d.roster.lastEmit>30000){d.emitRoster('own-player-missing',base);d.roster.lastEmit=at;}if(force||at-d.roster.lastEmit>30000){d.emitRoster('roster-health',Object.assign({},base,{selectors:snap.selectors,dom:snap.dom}));d.roster.lastEmit=at;}d.roster.ownWasPresent=snap.ownPresent;d.roster.last=snap;}catch(error){d.emitRoster('roster-error',{error:String(error&&error.message?error.message:error).slice(0,220),dom:d.domState()});}}",
        "window.__KISS_OBSERVE_ROSTER=observeRoster;setInterval(function(){observeRoster(false);},10000);setTimeout(function(){observeRoster(true);},1200);d.emitRoster('roster-installed',{dom:d.domState()});"
      ].join("")
    }
  ];
}

module.exports = {
  buildNetworkWatcherSteps
};

